name: Releases manual

on: workflow_dispatch

jobs:
  releases-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-latest,  # x86_64-linux
          ubuntu-24.04-arm,  # aarch64-linux

          macos-13,  # x86_64-darwin
          macos-15,  # aarch64-darwin
        ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 180
    environment:
      name: pypi
      url: https://pypi.org/p/gdb-for-pwndbg
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9  # @v3
    - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72  # @v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: build 310
      run: nix build '.#wheel.310' -o ./result310

    - name: build 311
      run: nix build '.#wheel.311' -o ./result311

    - name: build 312
      run: nix build '.#wheel.312' -o ./result312

    - name: build 313
      run: nix build '.#wheel.313' -o ./result313

    - name: build 314
      run: nix build '.#wheel.314' -o ./result314

    - name: dist
      run: |
        mkdir dist
        cp ./result310/*.whl ./dist/
        cp ./result311/*.whl ./dist/
        cp ./result312/*.whl ./dist/
        cp ./result313/*.whl ./dist/
        cp ./result314/*.whl ./dist/

    - name: Publish package distributions to PyPI
      run: |
        nix run nixpkgs#uv -- tool run twine upload dist/*
